"""socket update table

Revision ID: 140bee9f7c84
Revises: a0ab00995e9e
Create Date: 2024-05-21 21:05:41.025478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.db.models import UnixTimestamp

# revision identifiers, used by Alembic.
revision: str = '140bee9f7c84'
down_revision: Union[str, None] = 'a0ab00995e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latest_socket_update',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cg_id', sa.TEXT(), nullable=True),
    sa.Column('price_usd', sa.NUMERIC(), nullable=True),
    sa.Column('exchange', sa.TEXT(), nullable=True),
    sa.Column('updated_at', UnixTimestamp(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cg_id', name='socket_update_unique_coin_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('latest_socket_update')
    # ### end Alembic commands ###
