"""created_at_for_last_values

Revision ID: 49f04c52163e
Revises: 7fc75bb16321
Create Date: 2024-06-18 16:56:27.662889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f04c52163e'
down_revision: Union[str, None] = '7fc75bb16321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('last', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('last', 'created_at')
    # ### end Alembic commands ###
