"""exchnage field

Revision ID: 81bb3ed562ce
Revises: 4957e7c2d749
Create Date: 2024-04-23 11:50:51.846290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81bb3ed562ce'
down_revision: Union[str, None] = '4957e7c2d749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticker', 'exchange_id',
               existing_type=sa.SMALLINT(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticker', 'exchange_id',
               existing_type=sa.BIGINT(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
