"""ticker cols

Revision ID: 99408cf07cf9
Revises: a7ef5ada8a70
Create Date: 2024-05-08 16:49:15.505919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.db.models import UnixTimestamp


# revision identifiers, used by Alembic.
revision: str = '99408cf07cf9'
down_revision: Union[str, None] = 'a7ef5ada8a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker', sa.Column('on_create_id', sa.TEXT(), nullable=True))
    op.add_column('ticker', sa.Column('created_at', UnixTimestamp(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker', 'created_at')
    op.drop_column('ticker', 'on_create_id')
    # ### end Alembic commands ###
