"""order book table

Revision ID: a0ab00995e9e
Revises: d4366d5ad59a
Create Date: 2024-05-16 11:55:06.935249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from src.db.models import UnixTimestamp

# revision identifiers, used by Alembic.
revision: str = 'a0ab00995e9e'
down_revision: Union[str, None] = 'd4366d5ad59a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_book',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cg_id', sa.TEXT(), nullable=True),
    sa.Column('base', sa.TEXT(), nullable=True),
    sa.Column('quote', sa.TEXT(), nullable=True),
    sa.Column('exchange', sa.TEXT(), nullable=True),
    sa.Column('bids', postgresql.ARRAY(sa.NUMERIC()), nullable=True),
    sa.Column('asks', postgresql.ARRAY(sa.NUMERIC()), nullable=True),
    sa.Column('updated_at', UnixTimestamp(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cg_id', name='order_book_unique_coin_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_book')
    # ### end Alembic commands ###
