"""top_volume table

Revision ID: d4366d5ad59a
Revises: 99408cf07cf9
Create Date: 2024-05-15 17:37:56.075188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4366d5ad59a'
down_revision: Union[str, None] = '99408cf07cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_volume',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cg_id', sa.TEXT(), nullable=True),
    sa.Column('base', sa.TEXT(), nullable=True),
    sa.Column('quote', sa.TEXT(), nullable=True),
    sa.Column('volume_usd', sa.NUMERIC(), nullable=True),
    sa.Column('exchange', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cg_id', name='unique_coin_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_volume')
    # ### end Alembic commands ###
